<a href="https://colab.research.google.com/github/subhamsam007/Numpy-and-pandas/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Padas** **Series**\n
*A Series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index.*

#**Creating Series**
*There are multiple ways to create a pandas Series:*

In [2]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

# New Section
all about series

In [ ]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

# Data frames

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2= pd.DataFrame(data_list, columns=['test', 'Age', 'City', 'Salary'])
df2

    test  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

selecting and indexing of colums

In [5]:
df2

    test  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
df2[['test','City','Age']]

    test      City  Age
0   John  New York   28
1   Anna     Paris   34
2  Peter    Berlin   29
3  Linda    London   42

# How to create a new coloum inside data frame

In [17]:
df2['new_data']=['doc','eng','gg','dfsd']
df2

    test  Age      City  Salary new_data
0   John   28  New York   65000      doc
1   Anna   34     Paris   70000      eng
2  Peter   29    Berlin   62000       gg
3  Linda   42    London   85000     dfsd

Remove a coloumms

In [24]:
df2.drop('new_data',axis=1,inplace=True)
df2

    test  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000