<a href="https://colab.research.google.com/github/subhamsam007/Numpy-and-pandas/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Padas** **Series**\n
*A Series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index.*

#**Creating Series**
*There are multiple ways to create a pandas Series:*

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

# New Section
all about series

In [ ]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

# Data frames

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2= pd.DataFrame(data_list, columns=['test', 'Age', 'City', 'Salary'])
df2

    test  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

selecting and indexing of colums

In [ ]:
df2

    test  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2[['test','City','Age']]

    test      City  Age
0   John  New York   28
1   Anna     Paris   34
2  Peter    Berlin   29
3  Linda    London   42

# How to create a new coloum inside data frame

In [ ]:
df2['new_data']=['doc','eng','gg','dfsd']
df2

    test  Age      City  Salary new_data
0   John   28  New York   65000      doc
1   Anna   34     Paris   70000      eng
2  Peter   29    Berlin   62000       gg
3  Linda   42    London   85000     dfsd

Remove a coloumms

In [ ]:
df2.drop('new_data',axis=1,inplace=True)
df2

    test  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

selecting of rows

In [ ]:
df2.loc[3] # only for selecting one coloum

test       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [ ]:
df2.loc[[0,2]]

    test  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

selecting the subset of  rows and columms

In [ ]:
df2

    test  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc[[2,3]][["test","Age"]]

    test  Age
2  Peter   29
3  Linda   42

# condition selection

In [ ]:
#want to see those above 18
df2[df2['Age']>30]

    test  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
#want to see those above 18 and their salaries should be more than 70000
df2[(df2["Age"]>10) & (df2["Salary"]<70000)]

    test  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

# MISSING DATA

finding mising  data

In [ ]:

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
dtf=pd.DataFrame(data)
dtf

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
dtf.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
dtf.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
dtf.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

Now Removing The Missing Data

In [ ]:
dtf

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
dtf.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
# the df.dropna(axis=0, thresh=3) would drop any row that has fewer than 3 non-null values.
dtf.dropna(axis=1, thresh=3)

     A  B    C
0  1.0  1  1.0
1  2.0  2  2.0
2  NaN  3  3.0
3  4.0  4  NaN
4  5.0  5  NaN

now filling the miing value

In [ ]:
dtf.fillna(00)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
values = {"A":10,"B":100,"C":200,"D":400}
dtf.fillna(value = values)

      A  B      C      D
0   1.0  1    1.0    1.0
1   2.0  2    2.0  400.0
2  10.0  3    3.0  400.0
3   4.0  4  200.0  400.0
4   5.0  5  200.0    5.0

# now merging, Joining ,concatinating dataframes

**merging 2 data frames**

In [ ]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
#so now if we have to mearge then the same employee id the
pd.merge(employees,salaries,on='employee_id',how ='inner')
#

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
# now if we want to merge the whole id with the missing value as you can see in the output
pd.merge(employees,salaries,on='employee_id',how ='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

**contatination of 2 data frames**

In [ ]:

df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [ ]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
#so concat( is the function name)
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
#so now if i want to give axis then
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**joining of 2 data frames**

> Add blockquote

In [ ]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [ ]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [ ]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [ ]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

 # group by aggregation

In [4]:

data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [10]:
cat=df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [11]:
# group by multiple coloum and group by catagory and store
cat_store=df.groupby(['Category','Store'])['Sales'].sum()
cat_store

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

# pivot tables

In [22]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df=pd.DataFrame(data )
# df['MOnth']=df['Date'].dt.month-name()

df['Month'] = df['Date'].dt.month_name()
df['quater'] = "Q" +df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month quater
0  2023-01-01       A   East    127     86   John  January     Q1
1  2023-01-02       B   West    443     48   Mary  January     Q1
2  2023-01-03       C  North    805     21    Bob  January     Q1
3  2023-01-04       D  South    840     68  Alice  January     Q1
4  2023-01-05       A   East    963     46   John  January     Q1
5  2023-01-06       B   West    853     33   Mary  January     Q1
6  2023-01-07       C  North    646     98    Bob  January     Q1
7  2023-01-08       D  South    464     60  Alice  January     Q1
8  2023-01-09       A   East    661     24   John  January     Q1
9  2023-01-10       B   West    912     82   Mary  January     Q1
10 2023-01-11       C  North    314     83    Bob  January     Q1
11 2023-01-12       D  South    825     99  Alice  January     Q1
12 2023-01-13       A   East    110     71   John  January     Q1
13 2023-01-14       B   West    558     46   Mary  January     Q1
14 2023-01-15       C  North    131     61    Bob  January     Q1
15 2023-01-16       D  South    456     47  Alice  January     Q1
16 2023-01-17       A   East    916     54   John  January     Q1
17 2023-01-18       B   West    549     82   Mary  January     Q1
18 2023-01-19       C  North    350     94    Bob  January     Q1
19 2023-01-20       D  South    924     52  Alice  January     Q1

In [23]:
pd.pivot_table(df,index=['Product','Region'],values='Sales',aggfunc='sum')

                Sales
Product Region
A       East     2777
B       West     3315
C       North    2246
D       South    3509

# Data frames basic operations

In [25]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1.shape

(5, 3)

In [26]:

df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [27]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

** data frames applying function**

In [30]:
df1['D'] = df1["B"].apply(lambda x : x**2)

In [29]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500